/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface FastMorph {}
}

declare global {


  interface HTMLFastMorphElement extends Components.FastMorph, HTMLStencilElement {}
  var HTMLFastMorphElement: {
    prototype: HTMLFastMorphElement;
    new (): HTMLFastMorphElement;
  };
  interface HTMLElementTagNameMap {
    'fast-morph': HTMLFastMorphElement;
  }
}

declare namespace LocalJSX {
  interface FastMorph extends JSXBase.HTMLAttributes<HTMLFastMorphElement> {}

  interface IntrinsicElements {
    'fast-morph': FastMorph;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


