/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  FastMorph as FastMorph
} from './components/fast-morph/fast-morph';

declare global {
  interface HTMLFastMorphElement extends FastMorph, HTMLStencilElement {
  }
  var HTMLFastMorphElement: {
    prototype: HTMLFastMorphElement;
    new (): HTMLFastMorphElement;
  };
  interface HTMLElementTagNameMap {
    "fast-morph": HTMLFastMorphElement;
  }
  interface ElementTagNameMap {
    "fast-morph": HTMLFastMorphElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "fast-morph": JSXElements.FastMorphAttributes;
    }
  }
  namespace JSXElements {
    export interface FastMorphAttributes extends HTMLAttributes {
      
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
